#!/usr/bin/env python3

from core.aliases import *
from core import xmlConfigLoader, serviceStarter, serviceMonitorLoop


CONF_LOADER: xmlConfigLoader.xmlConfigLoader
PROC_NAME = "sbms-edge"


def main():
   try:
      global CONF_LOADER
      CONF_LOADER = xmlConfigLoader.xmlConfigLoader()
      if not CONF_LOADER.loadConfXMLs():
         print("\t--- sbms exiting ---")
         exit(1)
      # - - - - - - -
      print("\n\t--- sbms starting --")
      srvStarter: serviceStarter.serviceStarter = serviceStarter.serviceStarter(CONF_LOADER)
      srvStarter.loadInit()
      procs: ModbusProcessorList = srvStarter.start()
      if len(procs) == 0:
         print("\n\t--- sbms unable to start! ~ exiting --")
         exit(2)
      # - - - - - - -
      monitorLoop: serviceMonitorLoop.serviceMonitorLoop = \
         serviceMonitorLoop.serviceMonitorLoop(procs)
      monitorLoop.run()
   except Exception as e:
      print(e)


# - - - - - - entry point - - - - - -
if __name__ == "__main__":
   main()
