#!/usr/bin/env python3

import setproctitle
from typing import List
from core import xmlConfigLoader, serviceStarter,\
   serviceMonitorLoop, modbusProcess


CONF_LOADER: xmlConfigLoader.xmlConfigLoader
PROC_NAME = "openbms-edge"


def main():
   try:
      setproctitle.setproctitle(PROC_NAME)
      global CONF_LOADER
      CONF_LOADER = xmlConfigLoader.xmlConfigLoader()
      if not CONF_LOADER.loadConfXMLs():
         print("\t--- openbms exiting ---")
         exit(1)
      # - - - - - - -
      print("\n\t--- openbms starting --")
      srvStarter: serviceStarter.serviceStarter = \
         serviceStarter.serviceStarter(CONF_LOADER)
      srvStarter.loadInit()
      procs: List[modbusProcess.modbusProcess] = srvStarter.start()
      if len(procs) == 0:
         print("\n\t--- openbms unable to start! ~ exiting --")
         exit(2)
      # - - - - - - -
      monitorLoop: serviceMonitorLoop.serviceMonitorLoop = \
         serviceMonitorLoop.serviceMonitorLoop(procs)
      monitorLoop.run()
   except Exception as e:
      print(e)


# - - - - - - entry point - - - - - -
if __name__ == "__main__":
   main()
