#!/usr/bin/env python3

import sys, time
import minimalmodbus as mm


if len(sys.argv) == 1:
   print("\n\t./scanbus /dev/ttyUSBx adr-range baudrate parity timeout")
   print("\tie: ./scanbus /dev/ttyUSB1 10~20 9600 E 0.5\n")
   exit(0)

ttydev = sys.argv[1]
adrange = sys.argv[2].strip().split("~")
brate = int(sys.argv[3])
parity = sys.argv[4]
timeout = float(sys.argv[5])

inst = mm.Instrument(ttydev, 1)
inst.serial.baudrate = brate
inst.serial.parity = parity
inst.serial.timeout = timeout
inst.debug = True


def main():
   start, end = [int(x) for x in adrange]
   for i in range(start, end):
      try:
         time.sleep(0.64)
         print(f"scanning modbus address: {i} -> ", end="")
         inst.address = i
         val = inst.read_register(2)
         print(f" + response: {val}")
      except:
         print(" - no response!")


# - - - - - - - - - - - - - - - - - - - - - - - - -
if __name__ == "__main__":
    main()
